// frontend/vue/vue-project/src/features/expenses/components/ExpenseChart.vue
<script setup lang="ts">
import Chart from 'primevue/chart';
import { useExpenseStore } from "../stores/expense";
import { storeToRefs } from 'pinia';
import { computed } from 'vue';

const expenseStore = useExpenseStore();
const { expenses } = storeToRefs(expenseStore);

const chartData = computed(() => {
    const amountByCategory = expenses.value?.summary.amountByCategory || [];

    if (amountByCategory.length === 0) {
        return null;
    }
    const labels = amountByCategory.map(
        (item) => `${item.name} (${amountFormatter(item.amount)})`,
    );
    const data = amountByCategory.map((item) => item.amount);

    return {
        labels: labels,
        datasets: [
            {
                data: data,
                backgroundColor: [
                    '#FF6384',
                    '#36A2EB',
                    '#FFCE56',
                    '#4BC0C0',
                    '#9966FF',
                    '#FF9F40',
                    '#C9CBCF'
                ],
            }
        ]
    };
});

const options = {
    responsive: true,
    plugins: {
        legend: {
            position: 'bottom',
        },
        tooltip: {
            callbacks: {
                label: function (context: any) {
                    const label = context.label || '';
                    return label;
                }
            }
        }
    }
};

const amountFormatter = (value: number) => {
    const amount = parseFloat(value.toString());
    return new Intl.NumberFormat('fr-CA', {
        style: 'currency',
        currency: 'CAD',
    }).format(amount);
};

</script>

<template>
    <div class="expense-chart">
        <h2>Dépenses par catégorie</h2>
        <hr />
        <div class="chart-container">
            <Chart v-if="chartData" type="doughnut" :data="chartData" :options="options" />
            <p v-else>Aucune donnée disponible pour le graphique.</p>
        </div>
    </div>
</template>

<style lang="scss" scoped>
@use '../../../assets/scss/variables' as *;

.expense-chart {
    width: 100%;
    padding: 10px 20px;

    h2 {
        @include text-style(1.5rem, $color-1, 700);
        margin-bottom: 7px;

        @media (max-width: 1350px) {
            text-align: center;
        }
    }

    .chart-container {
        margin-top: 20px;
    }
}
</style>

// frontend/react/rtk-query-version/src/components/ExpenseChart.tsx
import "./ExpenseChart.scss";
import { PieChart, Pie, Tooltip, Legend, ResponsiveContainer } from "recharts";
import type { CategoryAmount } from "../models/expense/expenses";

const COLORS = [
  "#0088FE",
  "#00C49F",
  "#FFBB28",
  "#FF8042",
  "#AF19FF",
  "#FF4560",
  "#775DD0",
  "#546E7A",
  "#26a69a",
  "#D10CE8",
];

const ExpenseChart = ({ data }: { data: CategoryAmount[] }) => {
  const formattedData = data.map((item, index) => ({
    ...item,
    fill: COLORS[index % COLORS.length], // Recharts utilise automatiquement la clé "fill" de vos données
  }));

  const amountFormatter = (value: number) => {
    const amount = parseFloat(value.toString());
    return new Intl.NumberFormat("fr-CA", {
      style: "currency",
      currency: "CAD",
    }).format(amount);
  };

  const renderLegendText = (value: string, entry: any) => {
    // entry.payload contient l'objet d'origine (votre CategoryAmount + la clé fill)
    const amount = entry.payload?.amount ?? 0;
    return (
      <span className="legend-item">
        {value} : <strong>{amountFormatter(amount)}</strong>
      </span>
    );
  };

  return (
    <div className="expense-chart">
      <h2>Dépenses par catégéories</h2>
      <hr />
      <div className="chart-container">
        <ResponsiveContainer width="100%" height={550}>
          <PieChart margin={{ top: 20, bottom: 20, left: 30, right: 30 }}>
            <Pie
              data={formattedData}
              dataKey="amount"
              nameKey="name"
              cx="50%"
              cy="50%"
              outerRadius={120}
              fill="#8884d8"
              label={({ name, percent }) => {
                if (percent === undefined) return "";
                return percent > 0.05
                  ? `${name} ${(percent * 100).toFixed(0)}%`
                  : "";
              }}
            ></Pie>
            <Tooltip formatter={(value) => amountFormatter(value as number)} />
            <Legend
              iconType="circle"
              layout="vertical"
              align="center"
              verticalAlign="bottom" // Force la légende à se placer en bas
              formatter={renderLegendText}
            />
          </PieChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
};

export default ExpenseChart;
