// frontend/react/react-query-version-with-zustand/src/components/ExpenseToolbar.tsx
import "./ExpenseToolbar.scss";
import { useMemo, useState } from "react";
import AddExpenseModal from "../Modals/AddExpenseModal";
import { toast } from "react-hot-toast";
import { useCategories } from "../hooks/useCategory";
import useFiltersStore from "../stores/useFiltersStore";

const startYear = 1900;
const currentYear = new Date().getFullYear();
const years = [{ value: currentYear.toString(), label: currentYear.toString() }];
const months = [
  { value: "", label: "Aucun" },
  { value: 1, label: "Janvier" },
  { value: 2, label: "Février" },
  { value: 3, label: "Mars" },
  { value: 4, label: "Avril" },
  { value: 5, label: "Mai" },
  { value: 6, label: "Juin" },
  { value: 7, label: "Juillet" },
  { value: 8, label: "Août" },
  { value: 9, label: "Septembre" },
  { value: 10, label: "Octobre" },
  { value: 11, label: "Novembre" },
  { value: 12, label: "Décembre" },
];

for (let year = currentYear - 1; year >= startYear; year--) {
  years.push({
    value: year.toString(),
    label: year.toString(),
  });
}

const ExpenseToolbar = () => {
  const [open, setOpen] = useState(false);
  const { filters, setFilters } = useFiltersStore();
  const { data: categoriesData } = useCategories();
  const categories = useMemo(() => {
    const options = [{ value: "", label: "Toutes les catégories" }];
    categoriesData?.forEach((cat) => {
      options.push({ value: cat.id, label: cat.name });
    });

    return options;
  }, [categoriesData]);
  const daysInMonth = useMemo(() => {
    const month = parseInt(filters.month);
    const year = parseInt(filters.year);

    if (!month) return [{ value: "", label: "Aucun" }];

    const numberOfDays = new Date(year, month, 0).getDate();
    const newDays = [{ value: "", label: "Aucun" }];

    for (let day = 1; day <= numberOfDays; day++) {
      newDays.push({ value: day.toString(), label: day.toString() });
    }

    return newDays;
  }, [filters.month, filters.year]);

  const handleYearChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setFilters({
      year: e.target.value,
      day: "",
    });
  };

  const handleMonthChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setFilters({
      month: e.target.value,
      day: "",
    });
  };

  const handleDayChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setFilters({
      day: e.target.value,
    });
  };

  const handleCategoryChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setFilters({
      categoryId: e.target.value,
    });
  };

  const handleSaveSuccess = () => {
    setOpen(false);
    toast.success("Dépense ajoutée avec succès !");
  };

  const createDateString = () => {
    const day = filters.day ? String(filters.day).padStart(2, "0") : "01";
    const month = filters.month ? String(filters.month).padStart(2, "0") : "01";
    return `${filters.year}-${month}-${day}`;
  };

  return (
    <div className="expense-toolbar-container">
      <div className="expense-toolbar">
        <div className="form-group">
          <label htmlFor="year">Année</label>
          <select id="year" value={filters.year} onChange={handleYearChange}>
            {years.map((year) => (
              <option key={year.value} value={year.value}>
                {year.label}
              </option>
            ))}
          </select>
        </div>
        <div className="form-group">
          <label htmlFor="month">Mois</label>
          <select id="month" value={filters.month} onChange={handleMonthChange} className="border rounded px-2 py-1">
            {months.map((month) => (
              <option key={month.value} value={month.value}>
                {month.label}
              </option>
            ))}
          </select>
        </div>

        <div className="form-group">
          <label htmlFor="day">Jour</label>
          <select id="day" value={filters.day} onChange={handleDayChange}>
            {daysInMonth.map((day) => (
              <option key={day.value} value={day.value}>
                {day.label}
              </option>
            ))}
          </select>
        </div>
        <div className="form-group">
          <label htmlFor="category">Catégorie</label>
          <select id="category" value={filters.categoryId} onChange={handleCategoryChange}>
            {categories.map((category) => (
              <option key={category.value} value={category.value}>
                {category.label}
              </option>
            ))}
          </select>
        </div>
        <div className="form-group">
          <button onClick={() => setOpen(true)}>Ajouter une dépense</button>
        </div>
      </div>
      {open && (
        <AddExpenseModal
          categories={categories}
          categoryId={filters.categoryId}
          date={createDateString()}
          onClose={() => setOpen(false)}
          onSaveSuccess={() => {
            handleSaveSuccess();
          }}
        />
      )}
    </div>
  );
};

export default ExpenseToolbar;

// frontend/vue/vue-project - V2/src/features/expenses/components/ExpenseToolbar.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { useExpenseStore } from "../stores/expense";
import { useCategoryStore } from "../../categories/stores/category";
import { storeToRefs } from 'pinia';
import Select from 'primevue/select';
import ExpenseFormModal from "./ExpenseFormModal.vue";
import { useToast } from 'primevue/usetoast';

const expenseStore = useExpenseStore();
const { filters } = storeToRefs(expenseStore);
const { setYear, setMonth } = expenseStore;
const categoryStore = useCategoryStore();
const toast = useToast();
const START_YEAR = 1900;
const CURRENT_YEAR = new Date().getFullYear();
const months = [
    { value: "", label: "Aucun" },
    { value: "1", label: "Janvier" },
    { value: "2", label: "Février" },
    { value: "3", label: "Mars" },
    { value: "4", label: "Avril" },
    { value: "5", label: "Mai" },
    { value: "6", label: "Juin" },
    { value: "7", label: "Juillet" },
    { value: "8", label: "Août" },
    { value: "9", label: "Septembre" },
    { value: "10", label: "Octobre" },
    { value: "11", label: "Novembre" },
    { value: "12", label: "Décembre" },
];
const categories = computed(() => {
    const categories = categoryStore.categories;
    return [
        { value: '', label: 'Toutes les catégories' },
        ...categories.map((category) => ({ value: category.id, label: category.name })),
    ];
});

const daysInMonth = computed(() => {
    const month = parseInt(filters.value.month);
    const year = parseInt(filters.value.year);
    console.log("Calcul des jours pour le mois:", month, "et l'année:", year + " et le jour:", filters.value.day);
    if (!month) return [{ value: "", label: "Aucun" }];

    const numberOfDays = new Date(year, month, 0).getDate();
    const newDays = [{ value: "", label: "Aucun" }];

    for (let day = 1; day <= numberOfDays; day++) {
        newDays.push({ value: day.toString(), label: day.toString() });
    }

    return newDays;
});
const years = computed(() => {
    const result = [];
    for (let year = CURRENT_YEAR; year >= START_YEAR; year--) {
        result.push({ value: year.toString(), label: year.toString() });
    }
    return result;
});
const monthModel = computed({
    get: () => filters.value.month,
    set: (value) => setMonth(value)
})
const yearModel = computed({
    get: () => filters.value.year,
    set: (value) => setYear(value)
})
const dayModel = computed({
    // ⚠️ CAS SPÉCIAL PRIME VUE & CHAÎNE VIDE "" ⚠️
    // Problème : Si on change le mois, le jour doit revenir sur "" (Aucun). 
    // Cependant, PrimeVue n'accepte pas la chaîne vide "" via l'attribut 'optionValue' 
    // et affiche une case VIDE (blanc graphique) au lieu de sélectionner l'option "Aucun".
    // 
    // 💡 Alternative écartée : On aurait pu mettre le jour à 0 au lieu de "", ce qui fonctionne 
    // avec PrimeVue. Cependant, cela aurait obligé à modifier le type dans le store et à 
    // s'assurer de reconvertir le 0 en "" juste avant l'envoi au backend pour ne pas polluer l'API.
    //
    // ✔️ Solution retenue : On supprime 'optionValue' du HTML pour forcer PrimeVue à manipuler l'OBJET 
    // complet, ce qui contourne son bug interne sans impacter le store ni le backend.
    get: () => {
        const currentDayValue = filters.value.day;
        return daysInMonth.value.find(d => d.value === currentDayValue);
    },
    set: (selectedOption) => {
        filters.value.day = selectedOption ? selectedOption.value : "";
    }
});
const categoryModel = computed({
    // Même problème que pour le jour : PrimeVue ne gère pas la chaîne vide "" avec 'optionValue',
    get: () => {
        const currentCategoryId = filters.value.categoryId;
        return categories.value.find(c => c.value === currentCategoryId);
    },
    set: (selectedOption) => {
        filters.value.categoryId = selectedOption ? selectedOption.value : "";
    }
});

const isModalOpen = ref(false);

function handleSavedExpense() {
    isModalOpen.value = false;
    toast.add({ severity: 'success', summary: 'Succès', detail: 'Dépense enregistrée avec succès.', life: 3000 });
}

</script>

<template>
    <div class="expense-toolbar-container">
        <div class="expense-toolbar">
            <div class="form-group">
                <label for="year">Année</label>
                <Select v-model="yearModel" :options="years" optionLabel="label" optionValue="value"
                    class="select"></Select>
            </div>
            <div class="form-group">
                <label for="month">Mois</label>
                <Select v-model="monthModel" :options="months" optionLabel="label" optionValue="value"
                    class="select"></Select>
            </div>

            <div class="form-group">
                <label for="day">Jour</label>
                <Select v-model="dayModel" :options="daysInMonth" optionLabel="label" class="select"></Select>
            </div>

            <div class="form-group">
                <label for="category">Catégorie</label>
                <Select v-model="categoryModel" :options="categories" optionLabel="label" class="select"></Select>
            </div>
            <div class="form-group">
                <button @click="isModalOpen = true">Ajouter une dépense</button>
            </div>
        </div>
        <ExpenseFormModal v-if="isModalOpen" :expenseToEdit="null" @close="isModalOpen = false"
            @submit="handleSavedExpense" />
    </div>
</template>

<style lang="scss" scoped>
@use '../../../assets/scss/variables' as *;

.expense-toolbar {
    display: flex;
    padding: 16px 0;
    gap: 16px;

    @media (max-width: 1350px) {
        flex-direction: column;
        align-items: stretch;
    }

    .form-group {
        display: flex;
        flex-direction: column;

        @media (max-width: 1350px) {
            flex-direction: row;
            align-items: center;
            gap: 8px;
        }

        label,
        .select {
            color: $color-1;
            font-size: 1rem;
            font-weight: 500;
        }

        label {
            font-weight: 700;
        }

        label {
            @media (max-width: 1350px) {
                width: 100px;
            }
        }

        .select {
            width: 250px;
        }

        .select {
            @media (max-width: 1350px) {
                width: 100%;
            }
        }

        button {
            background-color: $color-1;
            color: #fff;
            border: none;
            padding: 8px 16px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1rem;
            font-weight: 500;
            margin-top: auto;

            @media (max-width: 1350px) {
                display: block;
                width: 100%;
            }

            &:hover {
                background-color: $background-color-3;
            }
        }
    }
}
</style>
